# Generated by Django 6.1.1 on 2026-09-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('rack_id', models.PositiveIntegerField()),
                ('retail_price', models.DecimalField(decimal_places=5, max_digits=8)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('geocode_source', models.CharField(blank=True, choices=[('local', 'Local city table'), ('nominatim', 'Nominatim'), ('', 'Not geocoded')], default='', max_length=20)),
            ],
            options={
                'ordering': ['opis_id'],
                'indexes': [models.Index(fields=['state', 'city'], name='station_state_city_idx'), models.Index(fields=['latitude', 'longitude'], name='station_latlng_idx')],
            },
        ),
    ]
